"""
run_fedavg_reliability.py

Run standard FedAvg under industrial client-reliability scenarios.

Scenarios consumed from:
    ../results/federated/dataset2_reliability/<scenario>/

Supported:
    clean
    sensor_noise
    stale_updates
    persistent_failure
    mixed

The model, optimizer, local training procedure, client partitions and
global test set remain the same as the validated FedAvg baseline.

This script changes ONLY the client-reliability condition.

Reliability effects:
    sensor_noise:
        Perturb affected client's input features during local training.

    stale_updates:
        Affected clients submit their previous-round local update when
        the schedule marks the client as stale. On the first round,
        no previous update exists, so the current update is used.

    persistent_failure:
        Affected clients are unavailable and do not participate.

    mixed:
        Applies any combination encoded in the schedule.

Important:
    The reliability_score generated by the simulator is logged but is
    NOT used by standard FedAvg. That score is reserved for the later
    proposed reliability-aware optimization.

Usage:
    python run_fedavg_reliability.py --scenario sensor_noise
    python run_fedavg_reliability.py --scenario stale_updates
    python run_fedavg_reliability.py --scenario persistent_failure
    python run_fedavg_reliability.py --scenario mixed

Optional:
    --rounds 15
    --local-epochs 1
    --batch-size 512
    --learning-rate 0.001
    --seed 42
"""

from __future__ import annotations

import argparse
import random
import time
from collections import OrderedDict
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.preprocessing import StandardScaler

from federated_model import build_model
from fedavg import (
    fedavg,
    get_feature_columns,
    train_local_model,
)


# ============================================================
# PATHS / CONFIGURATION
# ============================================================

CLIENT_DIR = Path(
    "../results/federated/dataset2_clients/noniid"
)

RELIABILITY_ROOT = Path(
    "../results/federated/dataset2_reliability"
)

GLOBAL_TEST_FILE = Path(
    "../results/federated/dataset2_clients/global_test.csv"
)

OUTPUT_ROOT = Path(
    "../results/federated/dataset2_fedavg_reliability"
)

N_CLIENTS = 10
DEFAULT_ROUNDS = 15
DEFAULT_LOCAL_EPOCHS = 1
DEFAULT_BATCH_SIZE = 512
DEFAULT_LEARNING_RATE = 0.001
DEFAULT_SEED = 42

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)


# ============================================================
# ARGUMENTS
# ============================================================

def parse_args():
    parser = argparse.ArgumentParser(
        description="Run standard FedAvg under industrial client unreliability."
    )

    parser.add_argument(
        "--scenario",
        choices=[
            "clean",
            "sensor_noise",
            "stale_updates",
            "persistent_failure",
            "mixed",
            "mixed_full",
        ],
        required=True,
    )

    parser.add_argument(
        "--rounds",
        type=int,
        default=DEFAULT_ROUNDS,
    )

    parser.add_argument(
        "--local-epochs",
        type=int,
        default=DEFAULT_LOCAL_EPOCHS,
    )

    parser.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_BATCH_SIZE,
    )

    parser.add_argument(
        "--learning-rate",
        type=float,
        default=DEFAULT_LEARNING_RATE,
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=DEFAULT_SEED,
    )

    return parser.parse_args()


# ============================================================
# REPRODUCIBILITY
# ============================================================

def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

    try:
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False
    except Exception:
        pass


# ============================================================
# MODEL SIZE
# ============================================================

def parameter_count(state_dict) -> int:
    return sum(
        tensor.numel()
        for tensor in state_dict.values()
        if torch.is_floating_point(tensor)
    )


def model_size_bytes(
    state_dict,
    bytes_per_parameter: int = 4,
) -> int:
    return (
        parameter_count(state_dict)
        * bytes_per_parameter
    )


# ============================================================
# LOAD CLIENTS / TEST
# ============================================================

def load_clients():
    clients = {}

    for client_id in range(1, N_CLIENTS + 1):

        path = (
            CLIENT_DIR
            / f"client_{client_id:02d}.csv"
        )

        if not path.exists():
            raise FileNotFoundError(
                f"Missing client file:\n"
                f"{path.resolve()}"
            )

        clients[client_id] = pd.read_csv(path)

    return clients


def load_global_test():
    if not GLOBAL_TEST_FILE.exists():
        raise FileNotFoundError(
            f"Missing global test file:\n"
            f"{GLOBAL_TEST_FILE.resolve()}"
        )

    return pd.read_csv(
        GLOBAL_TEST_FILE
    )


def load_reliability_schedule(
    scenario: str,
    rounds: int,
):
    path = (
        RELIABILITY_ROOT
        / scenario
        / "reliability_schedule.csv"
    )

    if not path.exists():
        raise FileNotFoundError(
            f"Missing reliability schedule:\n"
            f"{path.resolve()}\n"
            "Run simulate_industrial_client_reliability.py first."
        )

    schedule = pd.read_csv(path)

    required = {
        "round",
        "client_id",
        "available",
        "sensor_noise_multiplier",
        "stale_update",
        "staleness_rounds",
        "reliability_score",
    }

    missing = required - set(
        schedule.columns
    )

    if missing:
        raise ValueError(
            f"Schedule is missing columns: {sorted(missing)}"
        )

    schedule["round"] = (
        schedule["round"].astype(int)
    )
    schedule["client_id"] = (
        schedule["client_id"].astype(int)
    )
    schedule["available"] = (
        schedule["available"].astype(bool)
    )
    schedule["sensor_noise_multiplier"] = (
        schedule["sensor_noise_multiplier"].astype(float)
    )
    schedule["stale_update"] = (
        schedule["stale_update"].astype(bool)
    )
    schedule["staleness_rounds"] = (
        schedule["staleness_rounds"].astype(int)
    )
    schedule["reliability_score"] = (
        schedule["reliability_score"].astype(float)
    )

    schedule = schedule[
        schedule["round"] <= rounds
    ].copy()

    expected_rows = rounds * N_CLIENTS

    if len(schedule) != expected_rows:
        raise ValueError(
            f"Expected {expected_rows} schedule rows, "
            f"got {len(schedule)}."
        )

    return schedule.sort_values(
        ["round", "client_id"]
    ).reset_index(drop=True)


# ============================================================
# SCALING
# ============================================================

def prepare_data(
    clients,
    global_test,
):
    train_pool = pd.concat(
        list(clients.values()),
        ignore_index=True,
    )

    feature_columns = get_feature_columns(
        train_pool
    )

    scaler = StandardScaler()

    scaler.fit(
        train_pool[
            feature_columns
        ]
    )

    scaled_clients = {}

    for client_id, df in clients.items():
        scaled = df.copy()

        scaled[
            feature_columns
        ] = scaler.transform(
            df[
                feature_columns
            ]
        )

        scaled_clients[
            client_id
        ] = scaled

    scaled_test = global_test.copy()

    scaled_test[
        feature_columns
    ] = scaler.transform(
        global_test[
            feature_columns
        ]
    )

    return (
        scaled_clients,
        scaled_test,
        feature_columns,
    )


# ============================================================
# SENSOR NOISE
# ============================================================

def apply_sensor_noise(
    client_df: pd.DataFrame,
    feature_columns,
    noise_multiplier: float,
    seed: int,
):
    """
    Apply zero-mean Gaussian noise to a temporary local copy.

    Noise std for feature j:
        multiplier * std(feature_j)

    The client dataset saved on disk is never modified.
    """

    if noise_multiplier <= 0:
        return client_df

    rng = np.random.default_rng(
        seed
    )

    noisy = client_df.copy()

    values = noisy[
        feature_columns
    ].to_numpy(
        dtype=np.float32
    )

    feature_std = np.std(
        values,
        axis=0,
        ddof=0,
    )

    noise = rng.normal(
        loc=0.0,
        scale=noise_multiplier * (
            feature_std + 1e-12
        ),
        size=values.shape,
    ).astype(np.float32)

    noisy[
        feature_columns
    ] = values + noise

    return noisy


# ============================================================
# EVALUATION
# ============================================================

def evaluate_model(
    model,
    test_df,
    feature_columns,
):
    model.eval()

    X = torch.tensor(
        test_df[
            feature_columns
        ].to_numpy(
            dtype=np.float32
        ),
        dtype=torch.float32,
        device=DEVICE,
    )

    y = test_df[
        "label"
    ].to_numpy(
        dtype=np.int64
    )

    y_tensor = torch.tensor(
        y,
        dtype=torch.long,
        device=DEVICE,
    )

    criterion = torch.nn.CrossEntropyLoss()

    with torch.no_grad():
        logits = model(X)

        loss = criterion(
            logits,
            y_tensor,
        )

        probabilities = torch.softmax(
            logits,
            dim=1,
        )[:, 1]

        predictions = (
            probabilities >= 0.5
        ).long()

    y_pred = (
        predictions
        .cpu()
        .numpy()
    )

    y_prob = (
        probabilities
        .cpu()
        .numpy()
    )

    return {
        "global_test_loss": float(
            loss.item()
        ),
        "accuracy": float(
            accuracy_score(
                y,
                y_pred,
            )
        ),
        "precision": float(
            precision_score(
                y,
                y_pred,
                zero_division=0,
            )
        ),
        "recall": float(
            recall_score(
                y,
                y_pred,
                zero_division=0,
            )
        ),
        "f1": float(
            f1_score(
                y,
                y_pred,
                zero_division=0,
            )
        ),
        "roc_auc": float(
            roc_auc_score(
                y,
                y_prob,
            )
        ),
    }


# ============================================================
# STALE STATE MANAGEMENT
# ============================================================

def copy_state_dict(
    state,
):
    return OrderedDict(
        (
            name,
            tensor.detach().cpu().clone(),
        )
        for name, tensor in state.items()
    )


# ============================================================
# EXPERIMENT
# ============================================================

def run_experiment(
    scenario: str,
    rounds: int,
    local_epochs: int,
    batch_size: int,
    learning_rate: float,
    seed: int,
):
    set_seed(seed)

    clients = load_clients()
    global_test = load_global_test()

    schedule = load_reliability_schedule(
        scenario,
        rounds,
    )

    (
        scaled_clients,
        scaled_test,
        feature_columns,
    ) = prepare_data(
        clients,
        global_test,
    )

    model = build_model(
        input_size=len(feature_columns)
    ).to(DEVICE)

    global_state = copy_state_dict(
        model.state_dict()
    )

    model_bytes = model_size_bytes(
        global_state
    )

    # Stores the most recent usable local model state
    # for each client. This is used ONLY for the stale-update
    # stress test and is not an adaptive aggregation mechanism.
    previous_client_states = {}

    history = []

    print("=" * 78)
    print("FEDAVG INDUSTRIAL RELIABILITY EXPERIMENT")
    print("=" * 78)

    print(
        f"Scenario          : {scenario}"
    )

    print(
        f"Clients           : {N_CLIENTS}"
    )

    print(
        f"Rounds            : {rounds}"
    )

    print(
        f"Local epochs      : {local_epochs}"
    )

    print(
        f"Batch size        : {batch_size}"
    )

    print(
        f"Learning rate     : {learning_rate}"
    )

    print(
        f"Device            : {DEVICE}"
    )

    print(
        f"Model size        : {model_bytes} bytes"
    )

    for round_number in range(
        1,
        rounds + 1,
    ):

        round_start = time.perf_counter()

        round_schedule = schedule[
            schedule["round"] == round_number
        ]

        available_rows = round_schedule[
            round_schedule["available"]
        ]

        participating_ids = [
            int(x)
            for x in available_rows[
                "client_id"
            ].tolist()
        ]

        if not participating_ids:
            raise RuntimeError(
                f"No available clients in round {round_number}."
            )

        local_states = []
        local_counts = []
        local_losses = []

        actual_noisy_clients = 0
        actual_stale_clients = 0

        print()
        print("-" * 78)
        print(
            f"ROUND {round_number}/{rounds}"
        )

        print(
            "Available clients:",
            participating_ids,
        )

        # ----------------------------------------------------
        # Local training
        # ----------------------------------------------------

        for client_id in participating_ids:

            row = round_schedule[
                round_schedule["client_id"]
                == client_id
            ].iloc[0]

            client_seed = (
                seed
                + round_number * 1000
                + client_id
            )

            set_seed(
                client_seed
            )

            client_df = scaled_clients[
                client_id
            ]

            noise_multiplier = float(
                row[
                    "sensor_noise_multiplier"
                ]
            )

            stale_requested = bool(
                row["stale_update"]
            )

            # -----------------------------------------------
            # Apply sensor noise to this round's local data.
            # -----------------------------------------------

            if noise_multiplier > 0:

                actual_noisy_clients += 1

                client_df = apply_sensor_noise(
                    client_df=client_df,
                    feature_columns=feature_columns,
                    noise_multiplier=noise_multiplier,
                    seed=(
                        seed
                        + round_number * 10000
                        + client_id
                    ),
                )

            # -----------------------------------------------
            # Train current local model.
            # -----------------------------------------------

            (
                current_state,
                local_loss,
                sample_count,
            ) = train_local_model(
                global_state=global_state,
                client_df=client_df,
                device=DEVICE,
                input_size=len(
                    feature_columns
                ),
                local_epochs=local_epochs,
                learning_rate=learning_rate,
                batch_size=batch_size,
            )

            # -----------------------------------------------
            # Save current update as client's newest state.
            # -----------------------------------------------

            previous_state = (
                previous_client_states.get(
                    client_id
                )
            )

            previous_client_states[
                client_id
            ] = copy_state_dict(
                current_state
            )

            # -----------------------------------------------
            # Stale update simulation.
            #
            # If requested and a previous update exists,
            # submit the previous update instead of current.
            # -----------------------------------------------

            submitted_state = current_state
            stale_used = False

            if (
                stale_requested
                and previous_state is not None
            ):

                submitted_state = (
                    copy_state_dict(
                        previous_state
                    )
                )

                stale_used = True
                actual_stale_clients += 1

            local_states.append(
                submitted_state
            )

            local_counts.append(
                sample_count
            )

            local_losses.append(
                local_loss
            )

            status = []

            if noise_multiplier > 0:
                status.append(
                    f"noise={noise_multiplier:.2f}"
                )

            if stale_used:
                status.append(
                    "STALE_UPDATE"
                )

            if not status:
                status.append(
                    "normal"
                )

            print(
                f"Client {client_id:02d}: "
                f"samples={sample_count:3d} "
                f"loss={local_loss:.6f} "
                f"[{', '.join(status)}]"
            )

        # ----------------------------------------------------
        # Standard FedAvg.
        #
        # IMPORTANT:
        # No reliability score is used here.
        # ----------------------------------------------------

        aggregation_start = (
            time.perf_counter()
        )

        global_state = fedavg(
            local_states,
            local_counts,
        )

        aggregation_time = (
            time.perf_counter()
            - aggregation_start
        )

        model.load_state_dict(
            global_state
        )

        # ----------------------------------------------------
        # Evaluation
        # ----------------------------------------------------

        metrics = evaluate_model(
            model,
            scaled_test,
            feature_columns,
        )

        round_time = (
            time.perf_counter()
            - round_start
        )

        participating = len(
            participating_ids
        )

        failed = (
            N_CLIENTS
            - participating
        )

        # Communication is based on participating clients only.
        upload_bytes = (
            participating
            * model_bytes
        )

        download_bytes = (
            participating
            * model_bytes
        )

        total_communication = (
            upload_bytes
            + download_bytes
        )

        mean_reliability = float(
            round_schedule[
                round_schedule["available"]
            ]["reliability_score"]
            .mean()
        )

        history.append(
            {
                "scenario": scenario,
                "round": round_number,
                "available_clients": participating,
                "failed_clients": failed,
                "noisy_clients": actual_noisy_clients,
                "stale_clients": actual_stale_clients,
                "mean_reliability_available_clients": mean_reliability,
                "mean_local_loss": float(
                    np.mean(
                        local_losses
                    )
                ),
                "global_test_loss": metrics[
                    "global_test_loss"
                ],
                "accuracy": metrics[
                    "accuracy"
                ],
                "precision": metrics[
                    "precision"
                ],
                "recall": metrics[
                    "recall"
                ],
                "f1": metrics[
                    "f1"
                ],
                "roc_auc": metrics[
                    "roc_auc"
                ],
                "model_parameters": parameter_count(
                    global_state
                ),
                "model_size_bytes": model_bytes,
                "upload_bytes": upload_bytes,
                "download_bytes": download_bytes,
                "total_communication_bytes": total_communication,
                "aggregation_time_seconds": aggregation_time,
                "round_time_seconds": round_time,
            }
        )

        print(
            f"Global test loss : "
            f"{metrics['global_test_loss']:.6f}"
        )

        print(
            f"Accuracy         : "
            f"{metrics['accuracy']:.6f}"
        )

        print(
            f"Precision        : "
            f"{metrics['precision']:.6f}"
        )

        print(
            f"Recall           : "
            f"{metrics['recall']:.6f}"
        )

        print(
            f"F1               : "
            f"{metrics['f1']:.6f}"
        )

        print(
            f"ROC-AUC          : "
            f"{metrics['roc_auc']:.6f}"
        )

        print(
            f"Communication    : "
            f"{total_communication / (1024 ** 2):.4f} MiB"
        )

    return pd.DataFrame(
        history
    )


# ============================================================
# SAVE
# ============================================================

def save_results(
    history,
    scenario,
    args,
):

    output_dir = (
        OUTPUT_ROOT
        / scenario
    )

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    history.to_csv(
        output_dir
        / "fedavg_reliability_round_history.csv",
        index=False,
    )

    final = history.iloc[-1]

    total_communication = (
        history[
            "total_communication_bytes"
        ].sum()
    )

    final_metrics = pd.DataFrame(
        {
            "metric": [
                "scenario",
                "rounds",
                "clients",
                "local_epochs",
                "batch_size",
                "learning_rate",
                "seed",
                "final_accuracy",
                "final_precision",
                "final_recall",
                "final_f1",
                "final_roc_auc",
                "final_test_loss",
                "total_communication_bytes",
                "total_communication_mib",
                "total_round_time_seconds",
            ],
            "value": [
                scenario,
                args.rounds,
                N_CLIENTS,
                args.local_epochs,
                args.batch_size,
                args.learning_rate,
                args.seed,
                final["accuracy"],
                final["precision"],
                final["recall"],
                final["f1"],
                final["roc_auc"],
                final["global_test_loss"],
                total_communication,
                total_communication
                / (1024 ** 2),
                history[
                    "round_time_seconds"
                ].sum(),
            ],
        }
    )

    final_metrics.to_csv(
        output_dir
        / "fedavg_reliability_final_metrics.csv",
        index=False,
    )

    config = pd.DataFrame(
        {
            "parameter": [
                "scenario",
                "clients",
                "rounds",
                "local_epochs",
                "batch_size",
                "learning_rate",
                "seed",
                "device",
                "model",
                "input_features",
                "hidden_layers",
                "dropout",
                "aggregation",
            ],
            "value": [
                scenario,
                N_CLIENTS,
                args.rounds,
                args.local_epochs,
                args.batch_size,
                args.learning_rate,
                args.seed,
                str(DEVICE),
                "FederatedMLP",
                36,
                "128-64-32",
                0.40,
                "FedAvg",
            ],
        }
    )

    config.to_csv(
        output_dir
        / "fedavg_reliability_config.csv",
        index=False,
    )

    return output_dir


# ============================================================
# FIGURES
# ============================================================

def create_figures(
    history,
    scenario,
    output_dir,
):

    # --------------------------------------------------------
    # Classification metrics
    # --------------------------------------------------------

    fig, ax = plt.subplots(
        figsize=(10, 6)
    )

    for column, label in [
        ("accuracy", "Accuracy"),
        ("precision", "Precision"),
        ("recall", "Recall"),
        ("f1", "F1"),
        ("roc_auc", "ROC-AUC"),
    ]:

        ax.plot(
            history["round"],
            history[column],
            marker="o",
            linewidth=1.5,
            label=label,
        )

    ax.set_xlabel(
        "Federated round"
    )

    ax.set_ylabel(
        "Score"
    )

    ax.set_ylim(
        0,
        1.05,
    )

    ax.set_title(
        f"FedAvg — Industrial Reliability Scenario: {scenario}"
    )

    ax.grid(
        True,
        alpha=0.25,
    )

    ax.legend()

    fig.tight_layout()

    fig.savefig(
        output_dir
        / "metrics_vs_round.png",
        dpi=300,
        bbox_inches="tight",
    )

    plt.close(fig)

    # --------------------------------------------------------
    # Test loss and reliability
    # --------------------------------------------------------

    fig, ax1 = plt.subplots(
        figsize=(10, 6)
    )

    ax1.plot(
        history["round"],
        history["global_test_loss"],
        marker="o",
        label="Global test loss",
    )

    ax1.set_xlabel(
        "Federated round"
    )

    ax1.set_ylabel(
        "Global test loss"
    )

    ax1.grid(
        True,
        alpha=0.25,
    )

    ax2 = ax1.twinx()

    ax2.plot(
        history["round"],
        history[
            "mean_reliability_available_clients"
        ],
        linestyle="--",
        marker="s",
        label="Mean reliability",
    )

    ax2.set_ylabel(
        "Mean reliability score"
    )

    ax2.set_ylim(
        0,
        1.05,
    )

    ax1.set_title(
        f"FedAvg Loss and Reliability — {scenario}"
    )

    fig.tight_layout()

    fig.savefig(
        output_dir
        / "loss_and_reliability_vs_round.png",
        dpi=300,
        bbox_inches="tight",
    )

    plt.close(fig)

    # --------------------------------------------------------
    # Communication and availability
    # --------------------------------------------------------

    cumulative = (
        history[
            "total_communication_bytes"
        ].cumsum()
        / (1024 ** 2)
    )

    fig, ax1 = plt.subplots(
        figsize=(10, 6)
    )

    ax1.plot(
        history["round"],
        cumulative,
        marker="o",
        label="Cumulative communication",
    )

    ax1.set_xlabel(
        "Federated round"
    )

    ax1.set_ylabel(
        "Communication (MiB)"
    )

    ax1.grid(
        True,
        alpha=0.25,
    )

    ax2 = ax1.twinx()

    ax2.plot(
        history["round"],
        history["available_clients"],
        marker="s",
        linestyle="--",
        label="Available clients",
    )

    ax2.set_ylabel(
        "Available clients"
    )

    ax2.set_ylim(
        0,
        10.5,
    )

    ax1.set_title(
        f"FedAvg Communication and Availability — {scenario}"
    )

    fig.tight_layout()

    fig.savefig(
        output_dir
        / "communication_and_availability.png",
        dpi=300,
        bbox_inches="tight",
    )

    plt.close(fig)


# ============================================================
# MAIN
# ============================================================

def main():

    args = parse_args()

    if args.rounds <= 0:
        raise ValueError(
            "--rounds must be > 0."
        )

    if args.local_epochs <= 0:
        raise ValueError(
            "--local-epochs must be > 0."
        )

    if args.batch_size <= 0:
        raise ValueError(
            "--batch-size must be > 0."
        )

    if args.learning_rate <= 0:
        raise ValueError(
            "--learning-rate must be > 0."
        )

    set_seed(
        args.seed
    )

    history = run_experiment(
        scenario=args.scenario,
        rounds=args.rounds,
        local_epochs=args.local_epochs,
        batch_size=args.batch_size,
        learning_rate=args.learning_rate,
        seed=args.seed,
    )

    output_dir = save_results(
        history,
        args.scenario,
        args,
    )

    create_figures(
        history,
        args.scenario,
        output_dir,
    )

    final = history.iloc[-1]

    print()
    print("=" * 78)
    print("FEDAVG RELIABILITY EXPERIMENT COMPLETE")
    print("=" * 78)

    print(
        f"Scenario        : {args.scenario}"
    )

    print(
        f"Final accuracy  : "
        f"{final['accuracy']:.6f}"
    )

    print(
        f"Final precision : "
        f"{final['precision']:.6f}"
    )

    print(
        f"Final recall    : "
        f"{final['recall']:.6f}"
    )

    print(
        f"Final F1        : "
        f"{final['f1']:.6f}"
    )

    print(
        f"Final ROC-AUC   : "
        f"{final['roc_auc']:.6f}"
    )

    print(
        f"Final test loss : "
        f"{final['global_test_loss']:.6f}"
    )

    print(
        f"Total communication: "
        f"{history['total_communication_bytes'].sum() / (1024 ** 2):.4f} MiB"
    )

    print(
        "Results:",
        output_dir.resolve(),
    )

    print("=" * 78)


if __name__ == "__main__":
    main()
